import { abilities } from "./data";
import { AbilityPicker, ChoicesEditor, CsvInput, EffectsEditor, Field, LevelsEditor, Section, StringList, Toggle } from "./components";
import type { AbilityId, ForgeEntity, Locale } from "./types";

interface Props {
  entity: ForgeEntity;
  locale: Locale;
  onLocale: (locale: Locale) => void;
  onPatch: (patch: Partial<ForgeEntity>) => void;
}

const recoveryOptions = ["short_rest", "long_rest", "both", "dawn", "manual", "never"] as const;

export default function EntityEditor({ entity, locale, onLocale, onPatch }: Props) {
  const text = entity.localization[locale];
  const patchText = (patch: Partial<typeof text>) => onPatch({ localization: { ...entity.localization, [locale]: { ...text, ...patch } } });

  return <div className="entity-editor">
    <Section eyebrow="01 · Identity" title="Идентификация и локализация" actions={<div className="locale-tabs"><button className={locale === "ru" ? "active" : ""} onClick={() => onLocale("ru")} type="button">RU</button><button className={locale === "en" ? "active" : ""} onClick={() => onLocale("en")} type="button">EN</button></div>}>
      <div className="form-grid">
        <Field label="Технический ID" hint="Не меняется после публикации"><input value={entity.id} onChange={(event) => onPatch({ id: event.target.value })} /></Field>
        <Field label="Статус"><select value={entity.status} onChange={(event) => onPatch({ status: event.target.value as ForgeEntity["status"] })}>{["draft","review","published","deprecated"].map((status) => <option key={status}>{status}</option>)}</select></Field>
        <Field label={`Название _${locale}`} wide><input value={text.name} onChange={(event) => patchText({ name: event.target.value })} /></Field>
        <Field label={`Описание _${locale}`} wide><textarea rows={5} value={text.description} onChange={(event) => patchText({ description: event.target.value })} /></Field>
      </div>
    </Section>

    <Section eyebrow="02 · Provenance" title="Правила, источник и лицензия">
      <div className="form-grid three">
        <Field label="Ruleset ID"><input value={entity.rulesetId} onChange={(event) => onPatch({ rulesetId: event.target.value })} /></Field>
        <Field label="Source ID"><input value={entity.sourceId} onChange={(event) => onPatch({ sourceId: event.target.value })} /></Field>
        <Field label="Версия источника"><input value={entity.sourceVersion} onChange={(event) => onPatch({ sourceVersion: event.target.value })} /></Field>
        <Field label="License ID"><input value={entity.licenseId} onChange={(event) => onPatch({ licenseId: event.target.value })} /></Field>
        <Field label="Теги" wide><CsvInput value={entity.tags} onChange={(tags) => onPatch({ tags })} placeholder="official, srd52 или homebrew" /></Field>
      </div>
    </Section>

    {entity.entityType === "class" && <>
      <Section eyebrow="03 · Class core" title="Основа класса">
        <div className="form-grid three">
          <Field label="Кость хитов"><select value={entity.hitDie} onChange={(event) => onPatch({ hitDie: event.target.value as ForgeEntity["hitDie"] })}>{["d6","d8","d10","d12"].map((die) => <option key={die}>{die}</option>)}</select></Field>
          <Field label="Прогрессия заклинателя"><select value={entity.casterProgression} onChange={(event) => onPatch({ casterProgression: event.target.value as ForgeEntity["casterProgression"] })}>{["none","full","half_down","half_up","third","pact","custom"].map((value) => <option key={value}>{value}</option>)}</select></Field>
          <Field label="Характеристика заклинаний"><select value={entity.spellcastingAbility} onChange={(event) => onPatch({ spellcastingAbility: event.target.value as AbilityId | "" })}><option value="">—</option>{abilities.map((ability) => <option key={ability}>{ability}</option>)}</select></Field>
          <Field label="Основные характеристики" wide><AbilityPicker value={entity.primaryAbilities ?? []} onChange={(primaryAbilities) => onPatch({ primaryAbilities })} /></Field>
          <Field label="Требование мультикласса" wide hint="Всегда проверяется перед добавлением уровня"><input value={entity.multiclassPrerequisite} onChange={(event) => onPatch({ multiclassPrerequisite: event.target.value })} /></Field>
          <Field label="Хиты на 1 уровне"><input value={entity.startingHpFormula} onChange={(event) => onPatch({ startingHpFormula: event.target.value })} /></Field>
          <Field label="Хиты за уровень"><input value={entity.levelUpHpFormula} onChange={(event) => onPatch({ levelUpHpFormula: event.target.value })} /></Field>
          <Field label="Формула уровня заклинателя"><input value={entity.casterLevelFormula} onChange={(event) => onPatch({ casterLevelFormula: event.target.value })} /></Field>
          <Field label="Владения на 1 уровне" wide><CsvInput value={entity.startingProficiencies ?? []} onChange={(startingProficiencies) => onPatch({ startingProficiencies })} /></Field>
          <Field label="Владения при мультиклассе" wide><CsvInput value={entity.multiclassProficiencies ?? []} onChange={(multiclassProficiencies) => onPatch({ multiclassProficiencies })} /></Field>
        </div>
      </Section>
      <Section eyebrow="04 · Progression" title="Прогрессия 1–20"><LevelsEditor levels={entity.levels ?? []} onChange={(levels) => onPatch({ levels })} /></Section>
    </>}

    {entity.entityType === "subclass" && <Section eyebrow="03 · Subclass" title="Привязка и уровни"><div className="form-grid"><Field label="ID базового класса" wide><input value={entity.classId} onChange={(event) => onPatch({ classId: event.target.value })} /></Field></div><LevelsEditor title="Уровни подкласса" levels={entity.subclassLevels ?? []} onChange={(subclassLevels) => onPatch({ subclassLevels })} /></Section>}

    {entity.entityType === "species" && <>
      <Section eyebrow="03 · Species" title="Размер, скорости и чувства"><div className="form-grid"><Field label="Варианты размера"><CsvInput value={entity.sizeOptions ?? []} onChange={(sizeOptions) => onPatch({ sizeOptions })} /></Field><Field label="Скорость ходьбы, фт"><input type="number" min="0" value={entity.baseSpeeds?.walk ?? 0} onChange={(event) => onPatch({ baseSpeeds: { ...entity.baseSpeeds, walk: Number(event.target.value) } })} /></Field><Field label="Скорость полёта, фт"><input type="number" min="0" value={entity.baseSpeeds?.fly ?? 0} onChange={(event) => onPatch({ baseSpeeds: { ...entity.baseSpeeds, fly: Number(event.target.value) } })} /></Field><Field label="Скорость плавания, фт"><input type="number" min="0" value={entity.baseSpeeds?.swim ?? 0} onChange={(event) => onPatch({ baseSpeeds: { ...entity.baseSpeeds, swim: Number(event.target.value) } })} /></Field><Field label="ID умений" wide><CsvInput value={entity.featureIds ?? []} onChange={(featureIds) => onPatch({ featureIds })} /></Field></div></Section>
      <Section eyebrow="04 · Choices" title="Выборы вида"><ChoicesEditor choices={entity.choices ?? []} onChange={(choices) => onPatch({ choices })} /></Section>
    </>}

    {entity.entityType === "background" && <>
      <Section eyebrow="03 · Background" title="Характеристики, черта и владения"><div className="form-grid"><Field label="Ровно 3 характеристики" wide><AbilityPicker limit={3} value={entity.abilityOptions ?? []} onChange={(abilityOptions) => onPatch({ abilityOptions })} /></Field><Field label="ID черты"><input value={entity.featId} onChange={(event) => onPatch({ featId: event.target.value })} /></Field><Field label="Навыки, инструменты и языки"><CsvInput value={entity.proficiencyGrants ?? []} onChange={(proficiencyGrants) => onPatch({ proficiencyGrants })} /></Field></div></Section>
      <Section eyebrow="04 · Equipment" title="Комплекты снаряжения"><div className="cards-list">{(entity.equipmentOptions ?? []).map((option, index) => <article className="subcard" key={`${option.id}-${index}`}><header><strong>Комплект {index + 1}</strong><button className="icon-button danger" type="button" onClick={() => onPatch({ equipmentOptions: entity.equipmentOptions?.filter((_, itemIndex) => itemIndex !== index) })}>×</button></header><div className="form-grid"><Field label="ID комплекта"><input value={option.id} onChange={(event) => onPatch({ equipmentOptions: entity.equipmentOptions?.map((item, itemIndex) => itemIndex === index ? { ...item, id: event.target.value } : item) })} /></Field><Field label="Монеты, cp"><input type="number" min="0" value={option.currencyCp} onChange={(event) => onPatch({ equipmentOptions: entity.equipmentOptions?.map((item, itemIndex) => itemIndex === index ? { ...item, currencyCp: Number(event.target.value) } : item) })} /></Field><Field label="Предметы" wide hint="item.id:quantity через запятую"><input value={option.items.map((item) => `${item.itemId}:${item.quantity}`).join(", ")} onChange={(event) => onPatch({ equipmentOptions: entity.equipmentOptions?.map((item, itemIndex) => itemIndex === index ? { ...item, items: event.target.value.split(",").map((entry) => entry.trim()).filter(Boolean).map((entry) => { const [itemId, quantity] = entry.split(":"); return { itemId, quantity: Number(quantity || 1) }; }) } : item) })} /></Field></div></article>)}<button className="secondary-button" type="button" onClick={() => onPatch({ equipmentOptions: [...(entity.equipmentOptions ?? []), { id: `equipment.${(entity.equipmentOptions?.length ?? 0) + 1}`, items: [], currencyCp: 0 }] })}>+ Добавить комплект</button></div></Section>
      <Section eyebrow="05 · Choices" title="Дополнительные выборы"><ChoicesEditor choices={entity.choices ?? []} onChange={(choices) => onPatch({ choices })} /></Section>
    </>}

    {entity.entityType === "feat" && <>
      <Section eyebrow="03 · Feat" title="Категория и требования"><div className="form-grid"><Field label="Категория"><select value={entity.featCategory} onChange={(event) => onPatch({ featCategory: event.target.value as ForgeEntity["featCategory"] })}>{["origin","general","fighting_style","epic_boon","custom"].map((category) => <option key={category}>{category}</option>)}</select></Field><Toggle label="Можно брать повторно" checked={Boolean(entity.repeatable)} onChange={(repeatable) => onPatch({ repeatable })} /><Field label="ID связанных умений" wide><CsvInput value={entity.featureIds ?? []} onChange={(featureIds) => onPatch({ featureIds })} /></Field><Field label="Требования" wide><StringList value={entity.prerequisites ?? []} onChange={(prerequisites) => onPatch({ prerequisites })} placeholder="character_level() >= 4" /></Field></div></Section>
      <Section eyebrow="04 · Choices" title="Выборы черты"><ChoicesEditor choices={entity.choices ?? []} onChange={(choices) => onPatch({ choices })} /></Section>
    </>}

    {entity.entityType === "feature" && <>
      <Section eyebrow="03 · Feature" title="Режим и использование"><div className="form-grid three"><Field label="Тип умения"><select value={entity.mode} onChange={(event) => onPatch({ mode: event.target.value as ForgeEntity["mode"] })}>{["always_on","manual_unlimited","limited_use"].map((mode) => <option key={mode}>{mode}</option>)}</select></Field><Field label="Активация"><select value={entity.activation} onChange={(event) => onPatch({ activation: event.target.value as ForgeEntity["activation"] })}>{["none","action","bonus_action","reaction","free_action","special"].map((activation) => <option key={activation}>{activation}</option>)}</select></Field><Field label="Автоматизация"><select value={entity.automationLevel} onChange={(event) => onPatch({ automationLevel: event.target.value as ForgeEntity["automationLevel"] })}>{["full","partial","manual"].map((level) => <option key={level}>{level}</option>)}</select></Field><Field label="Требования" wide><StringList value={entity.prerequisites ?? []} onChange={(prerequisites) => onPatch({ prerequisites })} placeholder={'class_level("...") >= 3'} /></Field></div>{entity.mode === "limited_use" && <div className="resource-panel"><h3>Ресурс и восстановление</h3><div className="form-grid three"><Field label="Resource ID"><input value={entity.resource?.id ?? ""} onChange={(event) => onPatch({ resource: { id: event.target.value, maximumFormula: entity.resource?.maximumFormula ?? "1", recovery: entity.resource?.recovery ?? "long_rest", recoveryFormula: entity.resource?.recoveryFormula ?? "" } })} /></Field><Field label="Максимум"><input value={entity.resource?.maximumFormula ?? ""} onChange={(event) => onPatch({ resource: { id: entity.resource?.id ?? "resource.use", maximumFormula: event.target.value, recovery: entity.resource?.recovery ?? "long_rest", recoveryFormula: entity.resource?.recoveryFormula ?? "" } })} /></Field><Field label="Восстановление"><select value={entity.resource?.recovery ?? "long_rest"} onChange={(event) => onPatch({ resource: { id: entity.resource?.id ?? "resource.use", maximumFormula: entity.resource?.maximumFormula ?? "1", recovery: event.target.value as NonNullable<ForgeEntity["resource"]>["recovery"], recoveryFormula: entity.resource?.recoveryFormula ?? "" } })}>{recoveryOptions.map((recovery) => <option key={recovery}>{recovery}</option>)}</select></Field><Field label="Формула восстановления" wide><input value={entity.resource?.recoveryFormula ?? ""} onChange={(event) => onPatch({ resource: { id: entity.resource?.id ?? "resource.use", maximumFormula: entity.resource?.maximumFormula ?? "1", recovery: entity.resource?.recovery ?? "long_rest", recoveryFormula: event.target.value } })} /></Field></div></div>}</Section>
      <Section eyebrow="04 · Effects" title="Атомарные эффекты"><EffectsEditor entity={entity} onChange={(effects) => onPatch({ effects })} /></Section>
      <Section eyebrow="05 · Choices" title="Выборы умения"><ChoicesEditor choices={entity.choices ?? []} onChange={(choices) => onPatch({ choices })} /></Section>
    </>}

    {entity.entityType === "item" && <ItemEditor entity={entity} onPatch={onPatch} />}
    {entity.entityType === "spell" && <SpellEditor entity={entity} onPatch={onPatch} />}

    {entity.entityType === "reference" && <Section eyebrow="03 · Reference" title="Справочное значение"><div className="form-grid"><Field label="Категория"><select value={entity.referenceCategory} onChange={(event) => onPatch({ referenceCategory: event.target.value as ForgeEntity["referenceCategory"] })}>{["ability","skill","language","tool","damage_type","condition","sense","movement_type","size","rest_type","action_type","weapon_property","weapon_mastery","armor_training","spell_school"].map((category) => <option key={category}>{category}</option>)}</select></Field><Field label="Техническое значение JSON" wide><textarea rows={8} value={JSON.stringify(entity.referenceValue ?? {}, null, 2)} onChange={(event) => { try { onPatch({ referenceValue: JSON.parse(event.target.value) }); } catch { /* keep the last valid structured value */ } }} /></Field></div></Section>}
  </div>;
}

function ItemEditor({ entity, onPatch }: { entity: ForgeEntity; onPatch: (patch: Partial<ForgeEntity>) => void }) {
  const setType = (itemType: NonNullable<ForgeEntity["itemType"]>) => {
    const patch: Partial<ForgeEntity> = { itemType };
    if (itemType === "weapon" && !entity.weaponProfile) patch.weaponProfile = { category: "simple_melee", damage: "1d6", damageTypeId: "damage.slashing", scalingAbility: "str", rangeNormalFeet: 0, rangeLongFeet: 0, propertyIds: [], masteryId: "" };
    if (["armor", "shield"].includes(itemType) && !entity.armorProfile) patch.armorProfile = { category: itemType === "shield" ? "shield" : "light", baseAc: itemType === "shield" ? 2 : 11, addsDexterity: itemType !== "shield", maxDexterityBonus: 99, strengthRequirement: 0, stealthDisadvantage: false };
    onPatch(patch);
  };
  return <>
    <Section eyebrow="03 · Item" title="Физические и экономические параметры"><div className="form-grid three"><Field label="Тип предмета"><select value={entity.itemType} onChange={(event) => setType(event.target.value as NonNullable<ForgeEntity["itemType"]>)}>{["gear","weapon","armor","shield","tool","consumable","container","wondrous","currency","custom"].map((type) => <option key={type}>{type}</option>)}</select></Field><Field label="Вес, фунты"><input type="number" min="0" step="0.01" value={entity.weightLb} onChange={(event) => onPatch({ weightLb: Number(event.target.value) })} /></Field><Field label="Стоимость, cp"><input type="number" min="0" value={entity.costCp} onChange={(event) => onPatch({ costCp: Number(event.target.value) })} /></Field><Toggle label="Складывается в стопку" checked={Boolean(entity.stackable)} onChange={(stackable) => onPatch({ stackable })} /><Toggle label="Расходуемый" checked={Boolean(entity.consumable)} onChange={(consumable) => onPatch({ consumable })} /><Toggle label="Требует настройки" checked={Boolean(entity.requiresAttunement)} onChange={(requiresAttunement) => onPatch({ requiresAttunement })} /><Field label="Слоты экипировки" wide><CsvInput value={entity.equipmentSlots ?? []} onChange={(equipmentSlots) => onPatch({ equipmentSlots })} /></Field><Field label="Требования" wide><StringList value={entity.requirements ?? []} onChange={(requirements) => onPatch({ requirements })} placeholder={'ability_score("str") >= 13'} /></Field></div></Section>
    {entity.itemType === "weapon" && entity.weaponProfile && <Section eyebrow="04 · Weapon" title="Профиль оружия"><div className="form-grid three"><Field label="Категория"><select value={entity.weaponProfile.category} onChange={(event) => onPatch({ weaponProfile: { ...entity.weaponProfile!, category: event.target.value as NonNullable<ForgeEntity["weaponProfile"]>["category"] } })}>{["simple_melee","simple_ranged","martial_melee","martial_ranged","custom"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Урон"><input value={entity.weaponProfile.damage} onChange={(event) => onPatch({ weaponProfile: { ...entity.weaponProfile!, damage: event.target.value } })} /></Field><Field label="Тип урона"><input value={entity.weaponProfile.damageTypeId} onChange={(event) => onPatch({ weaponProfile: { ...entity.weaponProfile!, damageTypeId: event.target.value } })} /></Field><Field label="Характеристика"><select value={entity.weaponProfile.scalingAbility} onChange={(event) => onPatch({ weaponProfile: { ...entity.weaponProfile!, scalingAbility: event.target.value as NonNullable<ForgeEntity["weaponProfile"]>["scalingAbility"] } })}>{["str","dex","finesse","custom"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Обычная дистанция"><input type="number" min="0" value={entity.weaponProfile.rangeNormalFeet} onChange={(event) => onPatch({ weaponProfile: { ...entity.weaponProfile!, rangeNormalFeet: Number(event.target.value) } })} /></Field><Field label="Дальняя дистанция"><input type="number" min="0" value={entity.weaponProfile.rangeLongFeet} onChange={(event) => onPatch({ weaponProfile: { ...entity.weaponProfile!, rangeLongFeet: Number(event.target.value) } })} /></Field><Field label="Свойства" wide><CsvInput value={entity.weaponProfile.propertyIds} onChange={(propertyIds) => onPatch({ weaponProfile: { ...entity.weaponProfile!, propertyIds } })} /></Field><Field label="Мастерство"><input value={entity.weaponProfile.masteryId} onChange={(event) => onPatch({ weaponProfile: { ...entity.weaponProfile!, masteryId: event.target.value } })} /></Field></div></Section>}
    {["armor", "shield"].includes(entity.itemType ?? "") && entity.armorProfile && <Section eyebrow="04 · Armor" title="Профиль доспеха"><div className="form-grid three"><Field label="Категория"><select value={entity.armorProfile.category} onChange={(event) => onPatch({ armorProfile: { ...entity.armorProfile!, category: event.target.value as NonNullable<ForgeEntity["armorProfile"]>["category"] } })}>{["light","medium","heavy","shield","custom"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Базовый КД"><input type="number" min="0" value={entity.armorProfile.baseAc} onChange={(event) => onPatch({ armorProfile: { ...entity.armorProfile!, baseAc: Number(event.target.value) } })} /></Field><Field label="Макс. бонус Ловкости"><input type="number" min="0" value={entity.armorProfile.maxDexterityBonus} onChange={(event) => onPatch({ armorProfile: { ...entity.armorProfile!, maxDexterityBonus: Number(event.target.value) } })} /></Field><Field label="Требование Силы"><input type="number" min="0" value={entity.armorProfile.strengthRequirement} onChange={(event) => onPatch({ armorProfile: { ...entity.armorProfile!, strengthRequirement: Number(event.target.value) } })} /></Field><Toggle label="Добавляет Ловкость" checked={entity.armorProfile.addsDexterity} onChange={(addsDexterity) => onPatch({ armorProfile: { ...entity.armorProfile!, addsDexterity } })} /><Toggle label="Помеха Скрытности" checked={entity.armorProfile.stealthDisadvantage} onChange={(stealthDisadvantage) => onPatch({ armorProfile: { ...entity.armorProfile!, stealthDisadvantage } })} /></div></Section>}
    <Section eyebrow="05 · Charges" title="Заряды и восстановление"><div className="form-grid"><Toggle label="Использует заряды" checked={Boolean(entity.charges)} onChange={(enabled) => onPatch({ charges: enabled ? { maximumFormula: "1", recovery: "dawn" } : undefined })} />{entity.charges && <><Field label="Максимум зарядов"><input value={entity.charges.maximumFormula} onChange={(event) => onPatch({ charges: { ...entity.charges!, maximumFormula: event.target.value } })} /></Field><Field label="Восстановление"><select value={entity.charges.recovery} onChange={(event) => onPatch({ charges: { ...entity.charges!, recovery: event.target.value as NonNullable<ForgeEntity["charges"]>["recovery"] } })}>{recoveryOptions.map((value) => <option key={value}>{value}</option>)}</select></Field></>}</div></Section>
    <Section eyebrow="06 · Effects" title="Эффекты предмета"><EffectsEditor entity={entity} onChange={(effects) => onPatch({ effects })} /></Section>
  </>;
}

function SpellEditor({ entity, onPatch }: { entity: ForgeEntity; onPatch: (patch: Partial<ForgeEntity>) => void }) {
  return <>
    <Section eyebrow="03 · Spell" title="Уровень, школа и сотворение"><div className="form-grid three"><Field label="Уровень"><input type="number" min="0" max="9" value={entity.spellLevel} onChange={(event) => onPatch({ spellLevel: Number(event.target.value) })} /></Field><Field label="School ID"><input value={entity.schoolId} onChange={(event) => onPatch({ schoolId: event.target.value })} /></Field><Field label="Время"><select value={entity.casting?.actionType} onChange={(event) => onPatch({ casting: { ...entity.casting!, actionType: event.target.value as NonNullable<ForgeEntity["casting"]>["actionType"] } })}>{["action","bonus_action","reaction","minute","hour","special"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Количество"><input type="number" min="1" value={entity.casting?.value} onChange={(event) => onPatch({ casting: { ...entity.casting!, value: Number(event.target.value) } })} /></Field><Field label="Триггер реакции" wide><input value={entity.casting?.reactionTrigger} onChange={(event) => onPatch({ casting: { ...entity.casting!, reactionTrigger: event.target.value } })} /></Field></div></Section>
    <Section eyebrow="04 · Geometry" title="Дальность, область и длительность"><div className="form-grid three"><Field label="Тип дальности"><select value={entity.range?.type} onChange={(event) => onPatch({ range: { ...entity.range!, type: event.target.value as NonNullable<ForgeEntity["range"]>["type"] } })}>{["self","touch","distance","sight","unlimited","special"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Дистанция, фт"><input type="number" min="0" value={entity.range?.distanceFeet} onChange={(event) => onPatch({ range: { ...entity.range!, distanceFeet: Number(event.target.value) } })} /></Field><Field label="Форма области"><select value={entity.area?.shape} onChange={(event) => onPatch({ area: { ...entity.area!, shape: event.target.value as NonNullable<ForgeEntity["area"]>["shape"] } })}>{["none","cone","cube","cylinder","emanation","line","sphere","wall"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Размер области, фт"><input type="number" min="0" value={entity.area?.sizeFeet} onChange={(event) => onPatch({ area: { ...entity.area!, sizeFeet: Number(event.target.value) } })} /></Field><Field label="Длительность"><select value={entity.duration?.type} onChange={(event) => onPatch({ duration: { ...entity.duration!, type: event.target.value as NonNullable<ForgeEntity["duration"]>["type"] } })}>{["instant","rounds","minutes","hours","days","until_dispelled","special"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Значение"><input type="number" min="1" value={entity.duration?.value} onChange={(event) => onPatch({ duration: { ...entity.duration!, value: Number(event.target.value) } })} /></Field><Toggle label="Концентрация" checked={Boolean(entity.duration?.concentration)} onChange={(concentration) => onPatch({ duration: { ...entity.duration!, concentration } })} /></div></Section>
    <Section eyebrow="05 · Components" title="Компоненты и проверки"><div className="form-grid three"><Toggle label="Вербальный" checked={Boolean(entity.components?.verbal)} onChange={(verbal) => onPatch({ components: { ...entity.components!, verbal } })} /><Toggle label="Соматический" checked={Boolean(entity.components?.somatic)} onChange={(somatic) => onPatch({ components: { ...entity.components!, somatic } })} /><Toggle label="Материальный" checked={Boolean(entity.components?.material)} onChange={(material) => onPatch({ components: { ...entity.components!, material } })} /><Field label="Материал" wide><input value={entity.components?.materialText} onChange={(event) => onPatch({ components: { ...entity.components!, materialText: event.target.value } })} /></Field><Field label="Стоимость материала, cp"><input type="number" min="0" value={entity.components?.materialCostCp} onChange={(event) => onPatch({ components: { ...entity.components!, materialCostCp: Number(event.target.value) } })} /></Field><Toggle label="Расходуется" checked={Boolean(entity.components?.materialConsumed)} onChange={(materialConsumed) => onPatch({ components: { ...entity.components!, materialConsumed } })} /><Toggle label="Ритуал" checked={Boolean(entity.ritual)} onChange={(ritual) => onPatch({ ritual })} /><Field label="Тип атаки"><select value={entity.attackType} onChange={(event) => onPatch({ attackType: event.target.value as ForgeEntity["attackType"] })}>{["none","melee_spell","ranged_spell"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Спасбросок"><select value={entity.savingThrowAbility} onChange={(event) => onPatch({ savingThrowAbility: event.target.value as AbilityId | "" })}><option value="">—</option>{abilities.map((ability) => <option key={ability}>{ability}</option>)}</select></Field><Field label="Автоматизация"><select value={entity.automationLevel} onChange={(event) => onPatch({ automationLevel: event.target.value as ForgeEntity["automationLevel"] })}>{["full","partial","manual"].map((value) => <option key={value}>{value}</option>)}</select></Field></div></Section>
    <Section eyebrow="06 · Scaling" title="Масштабирование"><div className="cards-list">{(entity.scaling ?? []).map((scale, index) => <article className="subcard compact" key={`${scale.type}-${index}`}><Field label="Тип"><select value={scale.type} onChange={(event) => onPatch({ scaling: entity.scaling?.map((item, itemIndex) => itemIndex === index ? { ...item, type: event.target.value as typeof scale.type } : item) })}>{["character_level","spell_slot_level","class_level"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="На уровне"><input type="number" min="1" value={scale.at} onChange={(event) => onPatch({ scaling: entity.scaling?.map((item, itemIndex) => itemIndex === index ? { ...item, at: Number(event.target.value) } : item) })} /></Field><Field label="Значение"><input value={scale.value} onChange={(event) => onPatch({ scaling: entity.scaling?.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item) })} /></Field><button className="icon-button danger" type="button" onClick={() => onPatch({ scaling: entity.scaling?.filter((_, itemIndex) => itemIndex !== index) })}>×</button></article>)}<button className="secondary-button" type="button" onClick={() => onPatch({ scaling: [...(entity.scaling ?? []), { type: "spell_slot_level", at: 2, value: "1d6" }] })}>+ Добавить масштабирование</button></div></Section>
    <Section eyebrow="07 · Effects" title="Эффекты заклинания"><EffectsEditor entity={entity} onChange={(effects) => onPatch({ effects })} /></Section>
  </>;
}
