import type { Locale } from "./types";

const labels: Record<string, { en: string; ru: string }> = {
  draft: { en: "Draft", ru: "Черновик" },
  review: { en: "In review", ru: "На проверке" },
  published: { en: "Published", ru: "Опубликовано" },
  deprecated: { en: "Deprecated", ru: "Устарело" },
  none: { en: "None", ru: "Нет" },
  full: { en: "Full", ru: "Полная" },
  partial: { en: "Partial", ru: "Частичная" },
  manual: { en: "Manual", ru: "Ручная" },
  half_down: { en: "Half, round down", ru: "Половина, округление вниз" },
  half_up: { en: "Half, round up", ru: "Половина, округление вверх" },
  third: { en: "One third", ru: "Одна треть" },
  pact: { en: "Pact magic", ru: "Магия договора" },
  custom: { en: "Custom", ru: "Пользовательская" },
  origin: { en: "Origin", ru: "Происхождение" },
  general: { en: "General", ru: "Общая" },
  fighting_style: { en: "Fighting style", ru: "Боевой стиль" },
  epic_boon: { en: "Epic boon", ru: "Эпический дар" },
  always_on: { en: "Always active", ru: "Работает постоянно" },
  manual_unlimited: {
    en: "Activated, unlimited",
    ru: "Активируемое без ограничений",
  },
  limited_use: { en: "Limited uses", ru: "Ограниченное число применений" },
  action: { en: "Action", ru: "Действие" },
  bonus_action: { en: "Bonus action", ru: "Бонусное действие" },
  reaction: { en: "Reaction", ru: "Реакция" },
  free_action: { en: "Free action", ru: "Свободное действие" },
  special: { en: "Special", ru: "Особое" },
  short_rest: { en: "Short rest", ru: "Короткий отдых" },
  long_rest: { en: "Long rest", ru: "Долгий отдых" },
  both: { en: "Short or long rest", ru: "Короткий или долгий отдых" },
  dawn: { en: "At dawn", ru: "На рассвете" },
  turn_start: { en: "Start of turn", ru: "Начало хода" },
  initiative: { en: "When initiative is rolled", ru: "При броске инициативы" },
  initiative_or_rest: { en: "Initiative or rest", ru: "Инициатива или отдых" },
  never: { en: "Does not recover", ru: "Не восстанавливается" },
  reference: { en: "Reference", ru: "Справочное значение" },
  entity: { en: "Pack entity", ru: "Сущность пака" },
  number: { en: "Number", ru: "Число" },
  text: { en: "Text", ru: "Текст" },
  equipped: { en: "While equipped", ru: "Пока экипировано" },
  attuned: { en: "While attuned", ru: "Пока настроено" },
  on_event: { en: "On an event", ru: "При событии" },
  add: { en: "Add", ru: "Прибавить" },
  subtract: { en: "Subtract", ru: "Вычесть" },
  set: { en: "Set value", ru: "Установить значение" },
  set_minimum: { en: "Set minimum", ru: "Установить минимум" },
  set_maximum: { en: "Set maximum", ru: "Установить максимум" },
  multiply: { en: "Multiply", ru: "Умножить" },
  replace_formula: { en: "Replace formula", ru: "Заменить формулу" },
  grant: { en: "Grant", ru: "Выдать" },
  grant_proficiency: { en: "Grant proficiency", ru: "Выдать владение" },
  upgrade_proficiency: { en: "Upgrade proficiency", ru: "Повысить владение" },
  grant_advantage: { en: "Grant advantage", ru: "Дать преимущество" },
  grant_disadvantage: { en: "Grant disadvantage", ru: "Дать помеху" },
  create_resource: { en: "Create resource", ru: "Создать ресурс" },
  restore_resource: { en: "Restore resource", ru: "Восстановить ресурс" },
  "+": { en: "Add", ru: "Сложить" },
  "-": { en: "Subtract", ru: "Вычесть" },
  "*": { en: "Multiply", ru: "Умножить" },
  "/": { en: "Divide", ru: "Разделить" },
  "==": { en: "Equals", ru: "Равно" },
  "!=": { en: "Does not equal", ru: "Не равно" },
  ">": { en: "Greater than", ru: "Больше" },
  ">=": { en: "Greater than or equal", ru: "Больше или равно" },
  "<": { en: "Less than", ru: "Меньше" },
  "<=": { en: "Less than or equal", ru: "Меньше или равно" },
  and: { en: "And", ru: "И" },
  or: { en: "Or", ru: "Или" },
  contains: { en: "Contains", ru: "Содержит" },
  min: { en: "Use lowest", ru: "Взять меньшее" },
  max: { en: "Use highest", ru: "Взять большее" },
  floor: { en: "Round down", ru: "Округлить вниз" },
  ceil: { en: "Round up", ru: "Округлить вверх" },
  boolean: { en: "Yes / no", ru: "Да / нет" },
  string: { en: "Text", ru: "Текст" },
  formula: { en: "Formula", ru: "Формула" },
  dice: { en: "Dice", ru: "Кости" },
  sum: { en: "Add together", ru: "Складывать" },
  maximum: { en: "Use highest", ru: "Брать наибольшее" },
  minimum: { en: "Use lowest", ru: "Брать наименьшее" },
  replace: { en: "Replace previous", ru: "Заменять предыдущее" },
  non_stacking: { en: "Do not stack", ru: "Не складывать" },
  unique_by_source: { en: "One per source", ru: "Одно от каждого источника" },
  instant: { en: "Instant", ru: "Мгновенно" },
  rounds: { en: "Rounds", ru: "Раунды" },
  minutes: { en: "Minutes", ru: "Минуты" },
  hours: { en: "Hours", ru: "Часы" },
  days: { en: "Days", ru: "Дни" },
  until_rest: { en: "Until rest", ru: "До отдыха" },
  until_dispelled: { en: "Until dispelled", ru: "Пока не рассеяно" },
  permanent: { en: "Permanent", ru: "Постоянно" },
  self: { en: "Self", ru: "На себя" },
  touch: { en: "Touch", ru: "Касание" },
  distance: { en: "Distance", ru: "Дистанция" },
  sight: { en: "Sight", ru: "В пределах зрения" },
  unlimited: { en: "Unlimited", ru: "Неограниченная" },
  cone: { en: "Cone", ru: "Конус" },
  cube: { en: "Cube", ru: "Куб" },
  cylinder: { en: "Cylinder", ru: "Цилиндр" },
  emanation: { en: "Emanation", ru: "Эманация" },
  line: { en: "Line", ru: "Линия" },
  sphere: { en: "Sphere", ru: "Сфера" },
  wall: { en: "Wall", ru: "Стена" },
  melee_spell: { en: "Melee spell attack", ru: "Рукопашная атака заклинанием" },
  ranged_spell: {
    en: "Ranged spell attack",
    ru: "Дальнобойная атака заклинанием",
  },
  character_level: { en: "Character level", ru: "Уровень персонажа" },
  spell_slot_level: { en: "Spell slot level", ru: "Уровень ячейки" },
  class_level: { en: "Class level", ru: "Уровень класса" },
  damage: { en: "Damage", ru: "Урон" },
  healing: { en: "Healing", ru: "Лечение" },
  neutral: { en: "Other effect", ru: "Другой эффект" },
  ability: { en: "Ability", ru: "Характеристика" },
  skill: { en: "Skill", ru: "Навык" },
  language: { en: "Language", ru: "Язык" },
  tool: { en: "Tool", ru: "Инструмент" },
  damage_type: { en: "Damage type", ru: "Тип урона" },
  condition: { en: "Condition", ru: "Состояние" },
  sense: { en: "Sense", ru: "Чувство" },
  movement_type: { en: "Movement type", ru: "Тип перемещения" },
  size: { en: "Size", ru: "Размер" },
  rest_type: { en: "Rest type", ru: "Тип отдыха" },
  action_type: { en: "Action type", ru: "Тип действия" },
  weapon_property: { en: "Weapon property", ru: "Свойство оружия" },
  weapon_mastery: { en: "Weapon mastery", ru: "Мастерство оружия" },
  armor_training: { en: "Armor training", ru: "Владение доспехами" },
  spell_school: { en: "Spell school", ru: "Школа магии" },
  abjuration: { en: "Abjuration", ru: "Ограждение" },
  conjuration: { en: "Conjuration", ru: "Вызов" },
  divination: { en: "Divination", ru: "Прорицание" },
  enchantment: { en: "Enchantment", ru: "Очарование" },
  evocation: { en: "Evocation", ru: "Воплощение" },
  illusion: { en: "Illusion", ru: "Иллюзия" },
  necromancy: { en: "Necromancy", ru: "Некромантия" },
  transmutation: { en: "Transmutation", ru: "Преобразование" },
  gear: { en: "Adventuring gear", ru: "Снаряжение" },
  weapon: { en: "Weapon", ru: "Оружие" },
  armor: { en: "Armor", ru: "Доспех" },
  shield: { en: "Shield", ru: "Щит" },
  consumable: { en: "Consumable", ru: "Расходуемый предмет" },
  container: { en: "Container", ru: "Контейнер" },
  wondrous: { en: "Wondrous item", ru: "Чудесный предмет" },
  currency: { en: "Currency", ru: "Валюта" },
  spell_material: { en: "Spell material", ru: "Материал заклинания" },
  simple_melee: { en: "Simple melee weapon", ru: "Простое рукопашное оружие" },
  simple_ranged: { en: "Simple ranged weapon", ru: "Простое дальнобойное оружие" },
  martial_melee: { en: "Martial melee weapon", ru: "Воинское рукопашное оружие" },
  martial_ranged: { en: "Martial ranged weapon", ru: "Воинское дальнобойное оружие" },
  str: { en: "Strength", ru: "Сила" },
  dex: { en: "Dexterity", ru: "Ловкость" },
  finesse: { en: "Strength or Dexterity", ru: "Сила или Ловкость" },
  light: { en: "Light armor", ru: "Лёгкий доспех" },
  medium: { en: "Medium armor", ru: "Средний доспех" },
  heavy: { en: "Heavy armor", ru: "Тяжёлый доспех" },
  acid: { en: "Acid", ru: "Кислота" },
  bludgeoning: { en: "Bludgeoning", ru: "Дробящий" },
  cold: { en: "Cold", ru: "Холод" },
  fire: { en: "Fire", ru: "Огонь" },
  force: { en: "Force", ru: "Силовой" },
  lightning: { en: "Lightning", ru: "Электричество" },
  necrotic: { en: "Necrotic", ru: "Некротический" },
  piercing: { en: "Piercing", ru: "Колющий" },
  poison: { en: "Poison", ru: "Яд" },
  psychic: { en: "Psychic", ru: "Психический" },
  radiant: { en: "Radiant", ru: "Излучение" },
  slashing: { en: "Slashing", ru: "Рубящий" },
  thunder: { en: "Thunder", ru: "Звук" },
  cleave: { en: "Cleave", ru: "Рассечение" },
  graze: { en: "Graze", ru: "Скользящий удар" },
  nick: { en: "Nick", ru: "Быстрый удар" },
  push: { en: "Push", ru: "Толчок" },
  sap: { en: "Sap", ru: "Ослабление" },
  slow: { en: "Slow", ru: "Замедление" },
  topple: { en: "Topple", ru: "Опрокидывание" },
  vex: { en: "Vex", ru: "Отвлечение" },
  minute: { en: "Minute", ru: "Минута" },
  hour: { en: "Hour", ru: "Час" },
};

export function optionLabel(value: string, locale: Locale) {
  const direct = labels[value];
  if (direct) return direct[locale];
  const readable = value.replaceAll("_", " ").replaceAll(".", " › ").trim();
  return readable ? readable.charAt(0).toUpperCase() + readable.slice(1) : "—";
}
